{
 "title": "Netology 10.3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"nodeexporter:9100\",job=\"nodeexporter\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Free/Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "CPU Load Average 1/5/15",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) /  count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu)) * 100",
     "legendFormat": "Load Average 1m"
    },
    {
     "expr": "avg(node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) /  count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu)) * 100",
     "legendFormat": "Load Average 5m"
    },
    {
     "expr": "avg(node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) /  count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu)) * 100",
     "legendFormat": "Load Average 15m"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  }
 ]
}