---
# tasks file for roles/vector-role
- name: Vector | Install rpm
  become: true
  ansible.builtin.yum:
    name: "{{ vector_url }}"
    state: present
  tags: vector
- name: Vector | Template config
  ansible.builtin.template:
    src: vector.yml.j2
    dest: vector.yml
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  tags: vector
- name: Vector | create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  tags: vector
- name: Vector | Start service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  tags: vector
