apiVersion: 1

deleteDatasources:
  - name: prometheus-netology103
    orgId: 1

datasources:
- name: prometheus-netology103
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: false
  basicAuth: false