---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
      - name: Print custom var
        debug:
          msg: "{{ custom_var }}"
        when:
          - ansible_distribution == "Fedora"
